name: PlatformIO CI Release

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  release:
    runs-on: ubuntu-latest

    steps:
        - uses: actions/checkout@v4
        - uses: actions/cache@v4
          with:
            path: |
              ~/.cache/pip
              ~/.platformio/.cache
            key: ${{ runner.os }}-pio
  
        - uses: actions/setup-python@v5
          with:
            python-version: '3.11'
  
        - name: Install PlatformIO Core
          run: pip install --upgrade platformio
  
        - name: Build PlatformIO Project
          run: |
            pio run -e esp32-c3
            pio run -t buildfs -e esp32-c3

        - name: Upload binaries to release
          uses: softprops/action-gh-release@v2
          with:
            token: ${{ secrets.GITHUB_TOKEN }}
            fail_on_unmatched_files: true
            generate_release_notes: true
            make_latest: true
            files: |
              .pio/build/esp32-c3/bootloader.bin
              .pio/build/esp32-c3/partitions.bin
              .pio/build/esp32-c3/firmware.bin
              .pio/build/esp32-c3/spiffs.bin